For Munki simple bootstrap, have minutes threshold to give up if URL isn't set (#18)
* Add a max wait threshold to get URL set

* Update installer for script

* Do counter with max wait time

* Start counter at 0

* Move wait echo statement lower in while loop

* Make default wait minutes lower value

* Add wait time instructions to READMEs

diff --git a/minimal_bootstrap/package/scripts/postinstall b/minimal_bootstrap/package/scripts/postinstall
--- a/minimal_bootstrap/package/scripts/postinstall
+++ b/minimal_bootstrap/package/scripts/postinstall
@@ -1,7 +1,18 @@
 #!/bin/zsh
 
-munki_installer=/private/tmp/munkitools-6.6.3.4704.pkg
+# Maximum minutes to wait until SoftwareRepoURL set
+max_waiting_minutes=3
+
+# Convert minutes to seconds
+max_waiting_seconds=$((max_waiting_minutes * 60))
+
+# Path to installer
+munki_installer=/private/tmp/munkitools-6.6.5.4711.pkg
+
+# Line you expect to get back from SoftwareRepoURL setting
 url_test="SoftwareRepoURL: 'https://YOURORG.COM/munki_repo'"
+
+# Location of the managedsoftwareupdate command
 managedsoftwareupdate=/usr/local/munki/managedsoftwareupdate
 
 if [[ ! -f $munki_installer ]]; then
@@ -17,11 +28,19 @@ if [[ ! -f $managedsoftwareupdate ]]; then
     exit 1
 fi
 
+# Initialize counter in seconds waited
+counter=0
+
 # Presumably, the MDM would send down a configuration profile to set the Munki settings
 /bin/echo "Waiting for Munki settings..."
 while ! /usr/local/munki/managedsoftwareupdate --show-config | /usr/bin/grep "$url_test"; do
-    /bin/echo "$url_test not present yet. Waiting..."
+    if [[ $counter -gt $max_waiting_seconds ]]; then
+    	/bin/echo "ERROR: Waited more than $max_waiting_seconds for $url_test. Giving up..."
+    	exit 1
+    fi
     /bin/sleep 2
+    counter=$((counter + 2))
+    /bin/echo "$url_test not present yet. Waited $counter seconds so far..."
 done
 
 /bin/echo "$url_test now present!"
